### PR TITLE
RFC: run without linesearch by default in newton solver

### PR DESCRIPTION
**Pull request by KristofferC**
What do you think @spencerlyon2 

The backwards linesearch in Optim is almost always slower than the full newton for the problems I have tested.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
I'm happy with this change. 

What makes the line search slower?

**Comment by KristofferC** [comment]
Not sure why, maybe it is just on my type of problems or that the Optim function has a lot of overhead. No matter, it feels sensible to try a normal newton by default and if the user wants to enable a linesearch, it is very easy to enable.

**Comment by KristofferC** [comment]
If you are happy, then I am happy.

**Comment by spencerlyon2** [comment]
👍 looks good to me!

**Pull request merged**
