### PR TITLE
Also check for SingularException in jacobian inversion

### PR DESCRIPTION
**Pull request by timholy**
The added test fails on master, but a 1-line change fixes it.

### CODE REVIEW

**Comment by timholy** [comment]
I see this has a .travis.yml, but someone who's an owner on this repository needs to go to https://travis-ci.org/profile and flip the switch (and perhaps turn on the travis webhook here, under Settings).

**Comment by spencerlyon2** [comment]
Switch flipped

**Comment by timholy** [comment]
You're quick :smile:

**Comment by timholy** [comment]
Do you want me to rebase and force-push to see if Travis testing is now working?

**Comment by spencerlyon2** [comment]
Yeah, that'd be good. Might as well take it for a test drive :smile:

**Comment by timholy** [comment]
Now it's looking good.

**Comment by spencerlyon2** [comment]
Excellent, thanks for working on that. Looks good to me, but I'll let @sebastien-villemot  merge when he feels good about it.

**Pull request merged**
