### PR TITLE
change autodiff backend to ForwardDiff

### PR DESCRIPTION
**Pull request by KristofferC**
TODO before merge

- [x] Wait until a new version of ForwardDiff is tagged. There are some bugs that are fixed on master in ForwardDiff but needs a tag,

### CODE REVIEW

**Comment by KristofferC** [comment]
Pkg.checkout seems to resolve the packages so the `Distances` I moved to the test REQUIRE file gets removed. Anyway, I am tagging a new version of ForwardDiff now, will update this when it gets merged into METADATA.

**Comment by KristofferC** [comment]
ForwardDiff tagged and commits squashed and passing.

Need to get some good stuff to benchmark. Although I am pretty sure @jrevels and @mlubin has already done significant benchmarks comparisons between `DualNumbers` and `ForwardDiff` so maybe they can chime in.

**Comment by mlubin** [comment]
The default vector mode could be slower than ``DualNumbers``, you should use chunk mode but that's not fully general unless you set ``chunk_size=1``.

**Comment by jrevels** [comment]
> you should use chunk mode but that's not fully general unless you set chunk_size=1.

Details on this can be found in JuliaDiff/ForwardDiff.jl#36, if you're curious

**Comment by KristofferC** [comment]
Ok so I added an extra optional argument to `nlsolve` when using `:autodiff = true` which is the `chunk_size` that is defaulted to 1. I also added some small note in the README about `chunk_size` and a link to the ForwardDiff documentation about how to chose it.

**Comment by mlubin** [comment]
I don't think ``chunk_size`` should really be a user-facing option at this level. As soon as JuliaDiff/ForwardDiff.jl#36 is resolved you should be able to set ``chunk_size=10`` by default and forget about it.

**Comment by KristofferC** [comment]
So like this then by just setting `chunk_size` to 1 with a comment about https://github.com/JuliaDiff/ForwardDiff.jl/issues/36.

Would performance for this be on par with `DualNumbers`?

**Comment by mlubin** [comment]
Yes, performance should be about the same as ``DualNumbers`` in that case and the API is simpler, so still an overall win.

**Comment by spencerlyon2** [comment]
Thanks

**Comment by KristofferC** [comment]
Thanks for your valuable inputs @mlubin and @jrevels!

And thanks @spencerlyon2 for merge.

**Pull request merged**
