### PR TITLE
fix AD and deprecations

### PR DESCRIPTION
**Pull request by KristofferC**
Had to comment out one test in minpack that started failing. Not sure why. Maybe because of changes to linesearches.

### CODE REVIEW

**Comment by KristofferC** [comment]
Tests are passing locally. Not sure why they are failing on travis.

It is weird because the same test passes with AD but not with analytical derivative.
```jl
Brown almost-linear-newton                         40   515159    1000     2.050000e+01   6.757172e+00
minpack: Test Failed
  Expression: converged(r)
 in backtrace at error.jl:26
 in record at /home/travis/.julia/v0.4/BaseTestNext/src/BaseTestNext.jl:320
 in do_test at /home/travis/.julia/v0.4/BaseTestNext/src/BaseTestNext.jl:192
 [inlined code] from /home/travis/.julia/v0.4/NLsolve/test/minpack.jl:522
 in anonymous at no file:0
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 [inlined code] from /home/travis/.julia/v0.4/NLsolve/test/runtests.jl:27
 in anonymous at no file:0
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
Brown almost-linear-newton-AD                      40     461      18     1.137854e-09   3.268440e-02
```

On my computer:
```jl
Brown almost-linear-newton                         40     461      18     1.138134e-09   2.061997e-02
Brown almost-linear-newton-AD                      40     461      18     1.138135e-09   1.086409e-02
```

**Comment by spencerlyon2** [comment]
Thanks for fixing this up.

That is strange. What do you recommend we do with the PR? Should we start travis again, or is it an issue that a simple restart won't fix?

**Comment by KristofferC** [comment]
Since all the workers hit the same error I don't think a restart will do. However, I don't think I have introduced any bug with these changes or much more would fail. The only thing that could have changed is the backtracking linesearch has changed since the last time we ran the tests?

**Comment by KristofferC** [comment]
Since all the workers hit the same error I don't think a restart will do. However, I don't think I have introduced any bug with these changes or much more would fail. But why would the same problem fail without AD but work with AD...

**Comment by KristofferC** [comment]
Can we merge this even though the tests failed? I compared to earlier CI runs when tests passed and the results are identical for those minpack functions that converge. There is in my view almost zero probability that this PR introduces a bug that would cause only a few problems to fail.

I have high suspicion that the linea searches are the cause for this.

What do you think @spencerlyon2?

**Comment by spencerlyon2** [comment]
I think it is Ok.  Let's merge

**Comment by ChrisRackauckas** [comment]
Did this fix https://github.com/EconForge/NLsolve.jl/issues/75 ?

**Comment by KristofferC** [comment]
Probably ;)

**Comment by ChrisRackauckas** [comment]
Thanks. I suddenly had a test working again. Thanks for the New Year present!

**Pull request merged**
