### PR TITLE
remove unnecessary call to f!

### LINKED ISSUE #40: Double computing function value in Newton iterations due to backtracking
Not all linesearches in `Optim` returns the computed function value. Instead we unnecessarily have to recompute it, even though we just evaluated the function at the same point. https://github.com/EconForge/NLsolve.jl/blob/ff78c8e1323c0038db8a95a20ce8250bf3b9f86b/src/newton.jl#L130

We should probably look into getting the backtracking functions in Optim return the function value and we can then skip a function evaluation for each newton iteration.

### PR DESCRIPTION
**Pull request by KristofferC**
This is pretty funny...

Fixes #40

### CODE REVIEW

**Comment by KristofferC** [comment]
What we need to think about here is that we assume that the linesearch will actually evaluate the function. A user who passes his own line search along the lines of `linesearch!(x...) = 0.0, 0, 0` will be out of luck.

We should probably think about this and add it to the documentation.

**Comment by KristofferC** [comment]
Hmm, forgot that you can't overload keyword argument with type dispatch.. have to think of something else.

**Comment by KristofferC** [comment]
For now, I think it is fine if we document it and then tag a new 0.7 version. If anyone screams we can deal with it.

**Comment by spencerlyon2** [comment]
Sounds good to me.




// Spencer

On February 4, 2016 at 1:09:04 PM, Kristoffer Carlsson (notifications@github.com) wrote:

For now, I think it is fine if we document it and then tag a new 0.7 version. If anyone screams we can deal with it.

**Pull request merged**
